### ISSUE TITLE
Cannot install it [also feedback on touch end events]

### ISSUE THREAD

**Issue by nntantidakis** [idolize/logitech-craft-vscode#2]
I cannot install it as a plugin to Logitech options. Following your guidelines it makes the logioptions crash. Please add more details to the installation guide as this project is very futureproof!

**Comment by idolize** [comment]
Can you give more details on the crash? What OS are you using?

FYI, soon you will hopefully not have to follow all the manual build and install steps in the [dev guide](https://github.com/idolize/logitech-craft-vscode), as I'd like to publish the extensions more officially.

**Comment by idolize** [comment]
@nntantidakis Please take another look at the README now - the extension is officially published

**Comment by nntantidakis** [comment]
Hello. Im really sorry i havent replied to your previous comment, but i thought that i had replied.
I will try again and will inform you about it. Thanks a lot

**Comment by nntantidakis** [comment]
Works fine now, and its extremely useful! Thanks a lot! Just edit your plugin on vscode and remove the default action for crown release, its very confusing when you touch the crown and you see that it jumps 2 tabs in the beginning.

**Comment by idolize** [comment]
Hey @nntantidakis glad you got it working! So, crown touch/release is exactly what it sounds like: when you simply touch the crown it triggers. It's not when you *push* the crown (it seems like there is no event sent over the socket when pressed, unfortunately, although maybe it's possible to get it with a change in the tool config JSON for the Options plugin).

If you want to determine the difference between touching the crown just to trigger an action vs touching it to perform a rotation, we would have to modify the plugin slightly.

What about a "longTouch" event? This event would fire if you touch and hold the crown for 1 second (and thus if you quickly release or turn the crown then it won't trigger the longTouch event).

Here is a PR for you to review: https://github.com/idolize/logitech-craft-plugin/pull/1

**Comment by nntantidakis** [comment]
Maybe both of them will serve everyone nicely. If it's easy make the mod as customizable you want in order to serve more people. Personally, the longTouch event will not help me if i set it to be formatDocument. But i am not asking this modification for me only because i have already solved the problem by mapping another button and disabling the touch-release, im just mentioning some options in order to make it more usable.

**Comment by idolize** [comment]
Thanks for the feedback - I'll add both options to the plugin once I get a chance to test it and make sure it works.
