### ISSUE TITLE
Remote SSH/WSL support

### ISSUE THREAD

**Issue by gencer** [idolize/logitech-craft-vscode#30]
Is it possible to make this extension work with remotes? At least on WSL? Because WSL uses same host for IP and Port bindings.

Any possibility?

I've tried to install extension also on remote but it seems it just doesn't work out of the box.

**Comment by idolize** [comment]
@gencer the way the Logitech Options plugin system works is via a [port on localhost using websockets](https://github.com/idolize/logitech-craft-plugin/blob/master/src/CraftPlugin.ts#L5).

So, the extension needs to be able to talk to this IP/port of the computer that has Logitech Options installed.

I'm not too familiar with remote VS Code environments, but I'm assuming here that the computer running the VS Code extension is different from the one that has the Logitech Options server/keyboard attached? I could potentially expose a configurable option for the IP address, or if there is some VS Code documentation on how to get the remote IP then perhaps that could be used - although keep in mind the websocket port would also have to be open/accessible on that machine as well.

Can you provide more context on how this setup works and propose any possible solutions? I'm open to PRs in this repo or the [logitech-craft-plugin](https://github.com/idolize/logitech-craft-plugin) repo if they don't over-complicate things and are tested/working.

**Comment by gencer** [comment]
@idolize thank you for such a fast reply.

WSL is a bit different. WSL runs ubuntu linux inside of your Windows. Therefore they have same IP (127.0.0.1) and ports. Accessible without hassle. Remote SSH in the other hand is in another server or virtualbox. In this case, exposing port and assign ip is required. But for WSL they are on the same host.

but still, im unsure if we should expose port in some way or bind too 0.0.0.0 or something else. Because it *should* have been work already.

However, WSL has no access to C Drive directly. Instead we can see `C` drive in `/mnt/c/ProgramData/Logishrd/LogiOptionsPlugins/{UUID}`. (Every drive is mounted inside of `/mnt`. Like `/mnt/{c,d,e,f,g,...}`

I am playing with the extension's source code at the moment.

**Comment by gencer** [comment]
I also see this message in console:

```
[Extension Host] Activating connection to Logi Craft...
log.ts:197   ERR connect ECONNREFUSED 127.0.0.1:10134: Error: connect ECONNREFUSED 127.0.0.1:10134
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
```

**Comment by gencer** [comment]
@idolize It seems Windows can see all ports inside of WSL using `127.0.0.1` but not vice-versa.

I asked a question regarding to this on GitHub WSL repo. Let's see what they will say.

**Comment by gencer** [comment]
Well, It seems until they fix this issue we need to find a workaround. In Windows I mapped `10134` port to bind `0.0.0.0`. This makes my remote IP address accessible to the port.

So instead of `ws://127.0.0.1:10134` I changed it to `ws:/123.456.789:10134` (my remote ip).

Problem is, I can connect to this IP and port both locally and from WSL. But this plugin says `socket hang up`.

Is there a reason WebSocket fails on connect but i can connect both locally and remotely to this port?

**Comment by gencer** [comment]
@idolize Done! I've found the issue.

This guy: https://github.com/idolize/logitech-craft-plugin/blob/b1f02b4c1c166d819b07459a3c5cad2e06d1907c/src/CraftPlugin.ts#L10

See, WSL uses linux kernel. In your extension, Craft is finds process id for VSCode Server. But it should find my own Windows PID. I manually enter my Windowss porcess id there and it just did worked.

What we need to do is:

1. Use local network IP on WSL system. Like `192.168.1.10` or `10.0.0.1`... Instead of `127.0.0.1`
2. We need to use Windows Process ID instead of Linux/WSL process id.

I am working on second issue at the monent to find out how to grab Windows PID from WSL.

**Comment by gencer** [comment]
@idolize All we have to do is adding:


```json
  ...
  "extensionKind": "ui",
  ...
```

to the `package.json`. Then it works on SSH and WSL.
